build/tasks/build.js

add es6 css to the build, correct the build modules post merge, actually build the module
@PWKad @EisenbergEffect Updated the build and fixed my merge-mismatch from the last PR

chore(build)

---

README.md
src/dialog-renderer.js

attached the centerHorizontalOnly setting to the horizontal alignment
added the setting to the defaults for clarity
updated the docs to show the settings
@PWKad @EisenbergEffect Corrected the horizontal setting, and added some documentation around the settings.

fix(dialog-renderer)

---

src/dialog.html

Update broken `<link>` CSS import to `<require>` as per new framework features/changes

fix(dialog): Update link to `require`

---

src/styles/dialog.less

updated footer button to only show hover state when enabled, and made the button look disabled/ not  clickable when disabled.

updated footer button

---

src/dialog-renderer.js

https://github.com/aurelia/dialog/issues/68

Destroy modal only when modalContainer ends its transition

---

bower.json
config.js
package.json

Updated dependencies
This was causing forks in my project.

Updated dependencies

---

src/dialog-renderer.js
src/styles/dialog.less

fix(dialog): accessibility fixes

---

package.json

jspm@01.16.15 is needed to install depenedency
fixing https://github.com/aurelia/dialog/issues/99

chore(project): temporally set jspm version to 0.16.15

---

sample/package.json
src/dialog-controller.js

No issue number, just noticed this got left out from a recent set of commits.

fix(dialog-controller): remove promise pyramid of doom

---

build/paths.js
build/tasks/watch.js
sample/config.js
sample/package.json
src/dialog-configuration.js
src/dialog-controller.js
src/dialog-options.js
src/dialog-renderer.js
test/unit/dialog-renderer.spec.js

Renderer refactor

---

src/dialog-configuration.js
test/unit/dialog-configuration.spec.js

Undefined style should not get injected.
Added check for undefined style.
Added tests for empty style.

fix(dialog-configuration): Skip injecting empty style

---

README.md

all the Webpack issues have now been resolve and aurelia-dialog works OOTB
Fixes https://github.com/aurelia/dialog/issues/185

doc(README): remove Webpack specific settings

---

README.md

Added typings instructions to readme to avoid issues like #171 :smile:

chore(readme): mention typings install

---

src/dialog-configuration.js

fix(dialog-configuration): Add settings to configuration types and docs.

---

src/dialog-controller.js
test/unit/dialog-controller.spec.js

fix(dialog-controller): clear close promise when canDeactivate=>false

---

README.md

https://github.com/aurelia/dialog/issues/204

Update documentation about transitions

---

src/lifecycle.js
test/unit/lifecycle.spec.js

reject the promise chain with the error thrown by the invoked lifecycle method

fix(lefecycle): handle thrown errors

---

src/dialog-renderer.js
test/unit/dialog-renderer.spec.js

fix(dialog-renderer): check for transitions before awaiting transitonend

---

README.md
build/paths.js
src/dialog-cancel-error.js
src/dialog-controller.js
src/dialog-options.js
src/dialog-service.js
src/interfaces.js
src/lifecycle.js
test/unit/attach-focus.spec.js
test/unit/dialog-configuration.spec.js
test/unit/dialog-controller.spec.js
test/unit/dialog-renderer.spec.js
test/unit/dialog-service.spec.js
test/unit/index.spec.js
test/unit/lifecycle.spec.js

Starting point for #224, #223 
Will work on the tests after we clear the new open API.

feat(dialog-service): refactor consolidate open methods in one

---

src/ai-dialog-body.ts
src/ai-dialog-footer.ts
src/ai-dialog-header.ts
src/ai-dialog.ts
src/attach-focus.ts
src/aurelia-dialog.ts
src/dialog-cancel-error.ts
src/dialog-configuration.ts
src/dialog-controller.ts
src/dialog-renderer.ts
src/dialog-result.ts
src/dialog-service.ts
src/dialog-settings.ts
src/interfaces.ts
src/renderer.ts
test/unit/dialog-controller.spec.ts
test/unit/dialog-renderer.spec.ts
test/unit/dialog-service.spec.ts

~~remove "lock" setting~~
add "keyboard" setting
add "backdropDismiss" setting
add "showCloseButton" bindable property to ai-dialog-header

feat(all): decompose "lock" setting

---

src/aurelia-dialog.ts
src/dialog-configuration.ts
src/dialog-renderer.ts
src/ux-dialog-body.ts
src/ux-dialog-footer.ts
src/ux-dialog-header.ts
src/ux-dialog.ts
test/unit/dialog-configuration.spec.ts
test/unit/dialog-renderer.spec.ts

renamed the `ai` prefix to `ux` as discussed - `ai-dialog` => `ux-dialog`, `class AiDialog {}` = > `class UxDialog {}`

feat(all): switch prefix - "ai" => "ux"

---

src/dialog-configuration.ts

fix(dialog-configuration): use PLATFORM.moduleName

---

src/dialog-controller.ts

feat(dialog-controller): add object to canDeactivate / deactivate functions.

---

src/dialog-configuration.ts
test/unit/dialog-configuration.spec.ts

fix(dialog-configuration): set defaults for ".renderer" and ".cssText"

---

src/dialog-renderer.ts

The fix is for #294. This is not intended to fix issues where the `PAL` in not initialized correctly - like #295.

fix(dialog-renderer): lazy DOM access

---

doc/article/en-US/dialog-basics.md
doc/example/prompt.html

Added some notes related to #298.
@jods4 could you check if there is something I need to correct/rephrase/add?

doc(dialog-basics): add webpack notes

---

doc/article/en-US/dialog-basics.md

fixes https://github.com/aurelia/documentation/issues/346

fix(doc): correct link from dialog to bootstraping

---

doc/article/en-US/dialog-basics.md

Add information about the result parameter
Fixes issue: https://github.com/aurelia/dialog/issues/344

docs(hooks): canDeactivate result parameter

---

package-lock.json
package.json

chore(all): update aurelia-binding dependency

---

src/attach-focus.ts

Fixes same problem as these:
- i18n: aurelia/i18n@7c2a2d0
- validation: https://github.com/aurelia/validation/pull/496

fix(DI): use static method for Element

---

src/resources/attach-focus.ts
test/unit/attach-focus.spec.ts
test/unit/dialog-configuration.spec.ts

Initial discussion and PR #349

backport boolean attr behaviour for attach-focus

---

src/dialog-configuration.ts
src/resources/attach-focus.ts
src/resources/ux-dialog-body.ts
src/resources/ux-dialog-footer.ts
src/resources/ux-dialog-header.ts
src/resources/ux-dialog.ts
test/unit/dialog-configuration.spec.ts

Drop usage of `export default` for named exports.

Drop usage of "export default"

---

doc/article/en-US/dialog-basics.md
test/unit/attach-focus.spec.ts

ref https://github.com/aurelia/templating/pull/647#issuecomment-427989601

fix(doc): fix html5 syntax

---

.gitignore
package-lock.json
package.json
rollup.config.js
src/dialog-renderer.ts
src/resources/attach-focus.ts
src/resources/ux-dialog-body.ts
src/resources/ux-dialog-footer.ts
src/resources/ux-dialog-header.ts
src/resources/ux-dialog.ts

@StrahilKazlachev @EisenbergEffect 
This enables umd build for use in conjunction with aurelia script. Namespace of this plugin is `dialog`
```js
aurelia.use.plugin(aurelia.dialog.configure);
```

chore(build-umd): add umd build, remove use of decorators

---

rollup.config.js

@EisenbergEffect @StrahilKazlachev Sorry I misconfigured the build namespace

fix(build): correct namespace for umd build

---

karma.conf.js
package-lock.json
package.json

@EisenbergEffect the tests are failing because of less loading. Fixed

chore(tests): fix test less loading

---

src/aurelia-dialog.ts
src/dialog-settings.ts

Restore "restore focus types" and add missing export close #382

fix(settings): add missing types

---

README.md
src/dialog-settings.ts
src/renderers/native-dialog-renderer.ts
src/renderers/ux-dialog-renderer.ts
test/unit/aurelia-dialog.spec.ts
test/unit/native-dialog-renderer.spec.ts
test/unit/ux-dialog-renderer.spec.ts

Fixed bug for the dialog, where a mouse up event closes the dialog and results in unexpected UX behavior
Update and fixed README.md;

Fixed bug dialog mouse up event
