- config.js
- package.json
Just a small tidy up of dependencies.
`config.js` and `package.json` had dependencies on aurelia/modal (which is now the dialog repo). I have removed these as they are invalid here.
> refactor(config): remove deps for aurelia modal repo

- src/dialog-renderer.js
Keyup is a more browser-compatible event for handling the escape key. Keydown is also viable, if you prefer to handle it that way.
The keypress event is not firing in Chrome (OSX v43).
> fix: use keyup for escape key handler

- README.md
- build/paths.js
- build/tasks/serve.js
- build/tasks/watch.js
- config.js
- package.json
- sample/config.js
- sample/index.html
- sample/package.json
- sample/src/app.html
- sample/src/app.js
- sample/src/edit-person.html
- sample/src/edit-person.js
- sample/src/main.js
- src/dialog-controller.js
- src/index.js
Developer can now inspect the response and check the `wasCancelled`
property on the object returned.  It will return true or false depending
on whether it was cancelled or not.  The response will also now have an
`output` property that was previously simply the message.  Fixes #22.
> fix(cancel): allows cancelling dialog without throw

- src/dialog-renderer.js
The dialog did not auto-center on window resize. A CSS auto margin was used, but was being overwritten by `dialogController.centerDialog()`. Removing the lines of code setting an explicit margin-left inline style on the dialog container allows CSS to auto-center the modal even upon resize.
Fixes #55.
> fix(dialog): use CSS auto margins instead of JS

- src/styles/dialog.less
This disables pointer events on ai-dialog-container to enable the close click on ai-dialog-overlay.
without this css, the event listener here https://github.com/aurelia/dialog/blob/master/src/dialog-renderer.js#L66 never catches an event as the ai-dialog-container is on top of ai-dialog-overlay.
This solution only works for browsers supporting `pointer-events`: http://caniuse.com/#search=pointer-events
> disable pointer events on ai-dialog-container

- src/styles/dialog.less
fix: (issue #94) change dialog.less 
set the `pointer-events: none` to the overlay layer
prevent chrome on windows from adding a focus outline
> fix(dialog): allow response to click events

- README.md
- src/attach-focus.js
- test/unit/attach-focus.spec.js
Use the value of the attach-focus attribute to decide if the element is to be focused on attach. This allows using binding to alter the focused element.
> Attach focus value

- build/tasks/build.js
- src/dialog-controller.js
- f2a50056c4453b8717bc072b1e08488bab730880 : solves issue #82 and also exposes the `settings` attribute of `DialogController`
- 2f2ec7f8d7706e8fb8cd8ddbcc9443bc95bbeceb : minor change to `build.js`
- 017b5bf4555ca07e0fca1f9186728a78d14e4f4d : The `d.ts`  file is generated by a `gulp build`. This commit includes all the changes triggered by the `gulp build` command.
> Fix issue 82

- README.md
- config.js
- karma.conf.js
- package.json
- sample/src/app.html
- sample/src/app.js
- src/dialog-renderer.js
- test/fixtures/test-element.html
- test/unit/attach-focus.spec.js
- test/unit/dialog-controller.spec.js
- test/unit/dialog-renderer.spec.js
- test/unit/dialog-service.spec.js
- test/unit/index.spec.js
I didn't create an issue for this feature, since it is a pretty small change.
The motivation for this feature is to allow for the dialog plugin to also render 'pop-up' like dialogs.
The way I implemented this is by allowing you to pass in a `position` callback that the renderer uses to pass through the container and overlay. This callback is optional.
I believe this will allow issues like #84 to go away, as the caller can just implement this.
I have updated the sample to demonstrate what you can do with this.
I also updated the service tests. I'm not sure if that is something you want to test, but the only way to get through that promise chain in service.open is to include a few dev dependencies and setup the container.
Let me know your thoughts!
> feat(position): allow to pass in callback to do setup on elements

- src/dialog-service.js
- test/unit/dialog-service.spec.js
Dialog controllers were not tracked or destroyed by the service. Thus, there was no way to determine whether a dialog was active. We add a controllers array to the service to track all active dialog controllers, adding them upon dialog initialization and removing their reference when the `open` promise is resolved. This does not remove the collection from the renderer - it merely separates the concerns.
Fixes #121.
> feat(dialog): track controllers in service

- sample/config.js
- src/dialog-controller.js
- src/dialog-service.js
- src/renderers/dialog-renderer.js
- test/unit/attach-focus.spec.js
- test/unit/dialog-configuration.spec.js
- test/unit/dialog-controller.spec.js
- test/unit/dialog-renderer.spec.js
- test/unit/dialog-service.spec.js
- test/unit/index.spec.js
Change dialog renderer to use PAL. Alter DOM ordering of dialog elements and remove z-index ordering. Alter default renderer to be transient
Fixes #67. Fixes #70.
> refactor(dialog): refactor renderer and service

- src/dialog-service.js
Dialog Service was not adding the host element to the instruction passed to compose(). This fixes that issue.
Fixes #150.
> fix(dialog-service): add host element to container

- src/dialog-controller.js
The DialogResult class was missing an export keyword, making the class internal to the library. The babel-dts-generator does not generate types for classes that are not exported. Exporting the class fixes this issue without requiring an interface definition.
Fixes #134.
> fix(dialogResult): export DialogResult for dts

- test/unit/dialog-renderer.spec.js
renderer position test was raising console error: Unhandled promise
rejection TypeError: Cannot read property 'addEventListener' of null
> Fix renderer position test: avoid console error

- src/dialog-service.js
Is it possible to add 'view' to DialogService? 
Doesn't look like it would be much of a change. This way you could have separate views with the same view-model. Similar to how compose works.
`this.dialogService.open({ view: './add-item-input.html', viewModel: AddItem, model: { firstName: 'Owen', testScrolling: this.showExtraData }}).then((result) => {
if (!result.wasCancelled) {
console.log('good');
console.log(result.output);
} else {
console.log('bad');
}
});`
> Add view to DialogService

- src/dialog-service.js
We have a use case where we need to know if the DialogService has any active dialogs so that we can change our back button navigation handling.
We are consuming the code through TypeScript and need the hasActiveDialog and controllers exposed in the .d.ts
> Expose controllers and hasActiveDialog to TypeScript definitions

- src/dialog-configuration.js
Previously an empty `<style>` tag would be injected into the header if the
plugin was configured with no styling instructions.
> fix(dialog-configuration): do not inject empty styling

- src/dialog-configuration.js
- test/unit/dialog-configuration.spec.js
- test/unit/dialog-renderer.spec.js
- test/unit/index.spec.js
The renderer is now intended to be used per opened dialog (see 67e84f0). The configuration of the dialog plugin was not updated with that change and the registration of the renderer was still singleton. This PR updates the registration to transient.
closes aurelia/dialog#180
> fix(dialog-configuration): register renderer as transient

- src/dialog-service.js
- test/unit/dialog-service.spec.js
Correcting the promise chain in `.open()` to properly propagate errors.
> fix(dialog-service): .open() proper error propagation

- src/dialog-controller.js
- src/dialog-renderer.js
- src/dialog-service.js
- test/unit/dialog-renderer.spec.js
- test/unit/dialog-service.spec.js
fix #199, #207, #211 
From what I understand, currently the relationship renderer:controller should be 1:1, but the renderer is setup to track multiple controllers per instance. So when `ESC` is pressed every renderer closes its last controller - all controllers/dialogs get closed.
> fix(dialog-renderer): do not track controllers per renderer instance

- src/dialog-service.js
- test/unit/dialog-service.spec.js
- fix dialogs closed with `DialogController.error` should also be removed from `DialogService.controllers`
- fix controllers should be added to `DialogService.controllers` after the view model has activated(after `CompositionEngine.compose()` succeeds) - if not why is `DialogService.hasActiveDialog` computed from `DialogService.controllers.length`?
- refactor `DialogService.open()` to use `DialogService.openAndYieldController()` internally - nice for testing
- fix `reports no active dialog if no dialog is open` test
- add more tests
> fix(dialog-service): fix remove controllers closed with .error

- src/lifecycle.js
- test/unit/lifecycle.spec.js
The default value was applied only for sync implementations. `Promise.resolve()` will also handle `PromiseLike` results.
> fix(lifecycle): fix lifecycle methods default value

- README.md
- src/dialog-options.js
- src/dialog-renderer.js
- test/unit/dialog-renderer.spec.js
Adding ability to enable esc without `lock:false`.
Referenced: https://github.com/aurelia/dialog/issues/238
@PWKad
> feat(dialog options): allow esc to close dialog without lock: false

- src/dialog-cancel-error.js
- src/dialog-controller.js
- src/dialog-service.js
- src/lifecycle.js
- test/unit/dialog-controller.spec.js
- test/unit/dialog-renderer.spec.js
- test/unit/dialog-service.spec.js
Add a convenience method to close all open dialogs, see #214.
> feat(dialog-service): add .closeAll()

- src/dialog-renderer.ts
- src/dialog-service.ts
- src/dialog-settings.ts
- test/unit/dialog-renderer.spec.ts
- test/unit/dialog-service.spec.ts
- tslint.json
closes #260, closes #179, closes #220
* `host: Element` - if provided the `Renderer` will attach the dialog to this element, defaults to the `body`
* `childContainer: Container`
* the container in which the `DialogController` is registered and from which the `Renderer` is acquired
* if not provided a child container is created from the root `Container`
> feat: host and childContainer settings

- src/dialog-service.ts
- test/unit/dialog-service.spec.ts
Allowing for `rejectOnCancel` to be changed after `.open` has been called may lead to unexpected results.
```js
dialogService.open({rejectOnCancel: false}).whenClosed(result => {
if (result.wasCancelled) {
// do something important
return;
}
// do something else
});
```
Now if someone changes `rejectOnCancel` to `true` after the above has executed, the caller of `.open` will not be able to handle the cancellation.
@PWKad Does restricting the window for changes till `.open` is called seem reasonable?
> refactor(dialog-service): make "rejectOnCancel" readonly

- typings.json
Would this fix be sufficient to make this work again (#279)?
> fix(typings): location of main definition file is incorrect (fixes #279)

- src/dialog-close-error.ts
- src/dialog-controller.ts
- src/interfaces.ts
- test/unit/dialog-controller.spec.ts
- test/unit/dialog-service.spec.ts
Builds on top of #271 to provide consistent behavior to `DialogController.prototype.error` with the other *close* methods.
Main points of concern:
1. makes it easier to determine whether `DialogController.prototype.error` was called:
- in the `.deactivate` hook
- when `DialogController.prototype.error` is called, `.canDeactivate` is skipped.
- `.deactivate` will be called with either `DialogCloseResult` or `DialogCloseError`(instance of `Error`)
- in `dialogService.open({...}).whenClosed().catch()` - currently we can determine whether it is a cancellation error(`DialogCancelError`) or not(using just the error, without additional conventions, ...).
2. **breaking change** - currently `DialogController.prototype.error` accepts anything and rejects the result promise with that value. I …
> feat(dialog-controller): deactivate hook error data

- src/dialog-service.ts
- test/unit/dialog-service.spec.ts
When the `moduleId` of a given view model can not be resolved, reject with an error.
> fix(dialog-service): fix no fail for undefined moduleId

- src/aurelia-dialog.ts
- src/dialog-settings.ts
- src/native-dialog-renderer.ts
- test/unit/native-dialog-renderer.spec.ts
I wont repeat [everything I've already said in #335](https://github.com/aurelia/dialog/issues/335#issuecomment-359568900). 
This would finally close #1 and improve accessabilty.
**Breaking Changes**
- ~~`startingZIndex` setting is no longer required~~
- `position` callback is no longer passed overlay element as it no longer exists
- `centerHorizontalOnly` is not used. CSS only.
**To do**
> Add alternative <dialog> element renderer

- src/attach-focus.ts
- test/unit/attach-focus.spec.ts
make it work as boolean attribute
set the default binding mode to oneTime
update tests
> fix(attach-focus): restore behavior prior to #346

- doc/article/en-US/dialog-basics.md
The current documentation does not make it clear how styling is applied and can be overridden.  This PR adds brief details on how to go about customizing the css.
> add instructions on how to override dialog styles.

- src/dialog-renderer.ts
- src/dialog-settings.ts
- test/unit/dialog-renderer.spec.ts
when configuring the plugin one can pass the keyEvent as a setting, which accepts 'keyup' and 'keydown'.
Ported for v1
> feat(keyboard): allow to configure keyevent type

- package.json
- rollup.config.js
@fkleuver @huochunpeng @EisenbergEffect @StrahilKazlachev 
This PR adds an additional build target: `umd-es2015` for the combination of umd module format and es2015 version. Also adjust package.json so it won't cause any issues with IE11 when used without transpilation by pointing `module` field in package.json to `native-modules`
> fix(build): adjust umd build, add umd-es2015

- src/dialog-settings.ts
- src/renderers/native-dialog-renderer.ts
- src/renderers/ux-dialog-renderer.ts
- test/unit/native-dialog-renderer.spec.ts
- test/unit/ux-dialog-renderer.spec.ts
This controls where focus should be restored when a dialog closes.
By default focus is restored to the last element that was active when
the dialog opened.
Unfortunately the unit tests seem to broken at the moment (timeouts).
I've added a test based on existing ones but haven't seen it run succesfully.
Closes #375.
>  feat(renderers): add restoreFocus setting
